{
 "title": "EDC Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Finished Contract Negotiations by state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(state, service_name) (rate({service_name=~\".*edc.*\"} |~ `.*\\[CONSUMER\\] ContractNegotiation ([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}) is now in state ([A-Z].*)\\.` | json message=\"message\" | regexp `.*(?P<ID>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}) is now in state (?P<state>[A-Z].*)\\.` [$__auto]))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio",
     "legendFormat": "{{service.name}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{jvm_memory_type=\"heap\"}",
     "legendFormat": "{{service.name}} {{jvm_memory_pool_name}}"
    }
   ]
  },
  {
   "title": "Event Counter",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(service_name) (rate({service_name=~\".*edc.*\"} |= `AssetCreated` [24h]))",
     "legendFormat": "AssetCreated - {{service_name}}"
    },
    {
     "direction": "backward",
     "expr": "count by(service_name) (rate({service_name=~\".*edc.*\"} |= `PolicyDefinitionCreated` [$__auto]))",
     "legendFormat": "PolicyDefinitonCreated - {{service_name}}"
    },
    {
     "direction": "backward",
     "expr": "count by(service_name) (rate({service_name=~\".*edc.*\"} |= `ContractNegotiation` [$__auto]))",
     "legendFormat": "ContractNegotiation - {{service_name}}"
    }
   ]
  }
 ]
}